# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b06eb4a44e42578fbd9ac5ea099505d2702bc05018071daa448fb93e4862d7be56493ae7152a2cadea92441d0a4328941850291fd4aba6c7424a0f9580edad93

test:
  secret_key_base: cddd334d46eb1898793fcc65edc8d8778fea14af9204c112c88151ac1a52b91711a72d720c0551bb37d31caeb7b6bbc65e2b3460e9c2c3ef4f272243e76f9651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
